class Config:
    STUDENT_OS_VARIABLE = "STUDENTS_FILE"
    DISCIPLINE_OS_VARIABLE = "DISCIPLINES_FILE"
    GRADE_OS_VARIABLE = "GRADES_FILE"

    STUDENT_ID_FILE_INDEX = 0
    STUDENT_NAME_FILE_INDEX = 1

    DISCIPLINE_ID_FILE_INDEX = 0
    DISCIPLINE_NAME_FILE_INDEX = 1

    GRADE_ID_FILE_INDEX = 0
    GRADE_STUDENT_ID_FILE_INDEX = 1
    GRADE_DISCIPLINE_ID_FILE_INDEX = 2
    GRADE_VALUE_FILE_INDEX = 3

    DATA_FOLDER = "files_data/"
